import { v4 as uuidv4 } from 'uuid';
import PostDecoration from '../models/PostDecoration';
import { logger } from './logger';

/**
 * Decoration store items to seed on startup if none exist.
 * Includes backgrounds (light & dark), frames, and icon color sets.
 */
const decorationItems = [
  // ─── Light-Mode Backgrounds ───────────────────────────────────────────
  {
    name: 'Sunrise Bloom',
    category: 'background',
    themeMode: 'light',
    priceSkyCoins: 20,
    previewOrder: 1,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#FDDCB5', '#F8A4B8'],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#1F2937',
      captionColor: '#374151',
    }),
    isActive: true,
  },
  {
    name: 'Mint Breeze',
    category: 'background',
    themeMode: 'light',
    priceSkyCoins: 15,
    previewOrder: 2,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#A7F3D0', '#5EEAD4'],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#1F2937',
      captionColor: '#374151',
    }),
    isActive: true,
  },
  {
    name: 'Lavender Dream',
    category: 'background',
    themeMode: 'light',
    priceSkyCoins: 25,
    previewOrder: 3,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#DDD6FE', '#C4B5FD'],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#1F2937',
      captionColor: '#374151',
    }),
    isActive: true,
  },
  {
    name: 'Golden Hour',
    category: 'background',
    themeMode: 'light',
    priceSkyCoins: 30,
    previewOrder: 4,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#FDE68A', '#FB923C'],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#1F2937',
      captionColor: '#374151',
    }),
    isActive: true,
  },
  {
    name: 'Cotton Candy',
    category: 'background',
    themeMode: 'light',
    priceSkyCoins: 20,
    previewOrder: 5,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#FBCFE8', '#BFDBFE'],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#1F2937',
      captionColor: '#374151',
    }),
    isActive: true,
  },

  // ─── Dark-Mode Backgrounds ────────────────────────────────────────────
  {
    name: 'Midnight Ocean',
    category: 'background',
    themeMode: 'dark',
    priceSkyCoins: 20,
    previewOrder: 1,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#0F172A', '#134E4A'],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#F9FAFB',
      captionColor: '#D1D5DB',
    }),
    isActive: true,
  },
  {
    name: 'Dark Ember',
    category: 'background',
    themeMode: 'dark',
    priceSkyCoins: 25,
    previewOrder: 2,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#7F1D1D', '#1C1917'],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#F9FAFB',
      captionColor: '#D1D5DB',
    }),
    isActive: true,
  },
  {
    name: 'Twilight Violet',
    category: 'background',
    themeMode: 'dark',
    priceSkyCoins: 20,
    previewOrder: 3,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#4C1D95', '#1E1B4B'],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#F9FAFB',
      captionColor: '#D1D5DB',
    }),
    isActive: true,
  },
  {
    name: 'Obsidian Glow',
    category: 'background',
    themeMode: 'dark',
    priceSkyCoins: 15,
    previewOrder: 4,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#111827', '#064E3B'],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#F9FAFB',
      captionColor: '#D1D5DB',
    }),
    isActive: true,
  },
  {
    name: 'Cosmic Night',
    category: 'background',
    themeMode: 'dark',
    priceSkyCoins: 30,
    previewOrder: 5,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#312E81', '#0F172A'],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#F9FAFB',
      captionColor: '#D1D5DB',
    }),
    isActive: true,
  },

  // ─── Frames ───────────────────────────────────────────────────────────
  {
    name: 'Golden Classic',
    category: 'frame',
    themeMode: 'any',
    priceSkyCoins: 12,
    previewOrder: 1,
    styleData: JSON.stringify({
      borderWidth: 2,
      borderColor: '#D4A843',
      borderRadius: 16,
      shadowColor: '#B8860B',
      shadowOpacity: 0.3,
      shadowRadius: 8,
    }),
    isActive: true,
  },
  {
    name: 'Silver Lining',
    category: 'frame',
    themeMode: 'any',
    priceSkyCoins: 10,
    previewOrder: 2,
    styleData: JSON.stringify({
      borderWidth: 2,
      borderColor: '#C0C0C0',
      borderRadius: 16,
      shadowColor: '#A9A9A9',
      shadowOpacity: 0.3,
      shadowRadius: 8,
    }),
    isActive: true,
  },
  {
    name: 'Neon Pulse',
    category: 'frame',
    themeMode: 'any',
    priceSkyCoins: 15,
    previewOrder: 3,
    styleData: JSON.stringify({
      borderWidth: 2,
      borderColor: '#00FFFF',
      borderRadius: 16,
      shadowColor: '#00FFFF',
      shadowOpacity: 0.3,
      shadowRadius: 8,
    }),
    isActive: true,
  },
  {
    name: 'Rose Gold',
    category: 'frame',
    themeMode: 'any',
    priceSkyCoins: 12,
    previewOrder: 4,
    styleData: JSON.stringify({
      borderWidth: 2,
      borderColor: '#B76E79',
      borderRadius: 16,
      shadowColor: '#F4A7B9',
      shadowOpacity: 0.3,
      shadowRadius: 8,
    }),
    isActive: true,
  },
  {
    name: 'Electric Blue',
    category: 'frame',
    themeMode: 'any',
    priceSkyCoins: 10,
    previewOrder: 5,
    styleData: JSON.stringify({
      borderWidth: 2,
      borderColor: '#3B82F6',
      borderRadius: 16,
      shadowColor: '#2563EB',
      shadowOpacity: 0.3,
      shadowRadius: 8,
    }),
    isActive: true,
  },
  {
    name: 'Emerald Edge',
    category: 'frame',
    themeMode: 'any',
    priceSkyCoins: 8,
    previewOrder: 6,
    styleData: JSON.stringify({
      borderWidth: 2,
      borderColor: '#10B981',
      borderRadius: 16,
      shadowColor: '#059669',
      shadowOpacity: 0.3,
      shadowRadius: 8,
    }),
    isActive: true,
  },

  // ─── Icon Color Sets ──────────────────────────────────────────────────
  {
    name: 'Neon Pop',
    category: 'icon_color',
    themeMode: 'any',
    priceSkyCoins: 8,
    previewOrder: 1,
    styleData: JSON.stringify({
      likeColor: '#FF073A',
      commentColor: '#39FF14',
      shareColor: '#00FFFF',
      saveColor: '#FFFF00',
      giftColor: '#FF6EC7',
    }),
    isActive: true,
  },
  {
    name: 'Pastel Soft',
    category: 'icon_color',
    themeMode: 'any',
    priceSkyCoins: 5,
    previewOrder: 2,
    styleData: JSON.stringify({
      likeColor: '#F9A8D4',
      commentColor: '#A7F3D0',
      shareColor: '#BFDBFE',
      saveColor: '#FDE68A',
      giftColor: '#DDD6FE',
    }),
    isActive: true,
  },
  {
    name: 'Ocean Vibes',
    category: 'icon_color',
    themeMode: 'any',
    priceSkyCoins: 8,
    previewOrder: 3,
    styleData: JSON.stringify({
      likeColor: '#06B6D4',
      commentColor: '#14B8A6',
      shareColor: '#3B82F6',
      saveColor: '#0EA5E9',
      giftColor: '#22D3EE',
    }),
    isActive: true,
  },
  {
    name: 'Sunset Warmth',
    category: 'icon_color',
    themeMode: 'any',
    priceSkyCoins: 10,
    previewOrder: 4,
    styleData: JSON.stringify({
      likeColor: '#EF4444',
      commentColor: '#F97316',
      shareColor: '#F59E0B',
      saveColor: '#FB923C',
      giftColor: '#DC2626',
    }),
    isActive: true,
  },

  // ═══ THEME PACKS ═══════════════════════════════════════════════════
  // Each pack: light bg, dark bg, frame with corners, light icons (dark), dark icons (light)

  // ─── Cherry Blossom / Sakura ──────────────────────────────────────
  {
    name: 'Sakura Light',
    category: 'background',
    themeMode: 'light',
    priceSkyCoins: 25,
    previewOrder: 20,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#FDE4EC', '#F9A8D4', '#FBCFE8'],
      locations: [0, 0.5, 1],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#4A1942',
      captionColor: '#6B2152',
      cornerDecorations: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'flower',
        size: 20,
        color: '#BE185D',
        opacity: 0.5,
      },
      binderIcon: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'flower',
        color: 'rgba(190,24,93,0.6)',
      },
    }),
    isActive: true,
  },
  {
    name: 'Sakura Night',
    category: 'background',
    themeMode: 'dark',
    priceSkyCoins: 25,
    previewOrder: 20,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#2D0A2E', '#831843', '#4A1942'],
      locations: [0, 0.5, 1],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#FDE4EC',
      captionColor: '#F9A8D4',
      cornerDecorations: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'flower',
        size: 20,
        color: '#F9A8D4',
        opacity: 0.45,
      },
      binderIcon: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'flower',
        color: 'rgba(249,168,212,0.6)',
      },
    }),
    isActive: true,
  },
  {
    name: 'Sakura Frame',
    category: 'frame',
    themeMode: 'any',
    priceSkyCoins: 18,
    previewOrder: 20,
    styleData: JSON.stringify({
      borderWidth: 2,
      borderColor: '#F9A8D4',
      borderRadius: 16,
      shadowColor: '#EC4899',
      shadowOpacity: 0.3,
      shadowRadius: 10,
      cornerDecorations: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'flower',
        size: 18,
        color: '#EC4899',
        opacity: 0.75,
      },
    }),
    isActive: true,
  },
  {
    name: 'Sakura Icons Light',
    category: 'icon_color',
    themeMode: 'light',
    priceSkyCoins: 10,
    previewOrder: 20,
    styleData: JSON.stringify({
      likeColor: '#9D174D',
      commentColor: '#BE185D',
      shareColor: '#831843',
      saveColor: '#701A3E',
      giftColor: '#DB2777',
    }),
    isActive: true,
  },
  {
    name: 'Sakura Icons Dark',
    category: 'icon_color',
    themeMode: 'dark',
    priceSkyCoins: 10,
    previewOrder: 20,
    styleData: JSON.stringify({
      likeColor: '#F9A8D4',
      commentColor: '#FBCFE8',
      shareColor: '#F472B6',
      saveColor: '#FDA4AF',
      giftColor: '#FDE4EC',
    }),
    isActive: true,
  },

  // ─── Garden / Floral ──────────────────────────────────────────────
  {
    name: 'Garden Light',
    category: 'background',
    themeMode: 'light',
    priceSkyCoins: 25,
    previewOrder: 21,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#DCFCE7', '#BBF7D0', '#FDE4EC'],
      locations: [0, 0.6, 1],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#14532D',
      captionColor: '#166534',
      cornerDecorations: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'leaf',
        size: 20,
        color: '#166534',
        opacity: 0.45,
      },
      binderIcon: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'leaf',
        color: 'rgba(22,101,52,0.55)',
      },
    }),
    isActive: true,
  },
  {
    name: 'Garden Night',
    category: 'background',
    themeMode: 'dark',
    priceSkyCoins: 25,
    previewOrder: 21,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#052E16', '#14532D', '#1C1917'],
      locations: [0, 0.5, 1],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#DCFCE7',
      captionColor: '#BBF7D0',
      cornerDecorations: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'leaf',
        size: 20,
        color: '#86EFAC',
        opacity: 0.4,
      },
      binderIcon: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'leaf',
        color: 'rgba(134,239,172,0.55)',
      },
    }),
    isActive: true,
  },
  {
    name: 'Garden Frame',
    category: 'frame',
    themeMode: 'any',
    priceSkyCoins: 18,
    previewOrder: 21,
    styleData: JSON.stringify({
      borderWidth: 2,
      borderColor: '#4ADE80',
      borderRadius: 16,
      shadowColor: '#22C55E',
      shadowOpacity: 0.3,
      shadowRadius: 10,
      cornerDecorations: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'leaf',
        size: 18,
        color: '#22C55E',
        opacity: 0.75,
      },
    }),
    isActive: true,
  },
  {
    name: 'Garden Icons Light',
    category: 'icon_color',
    themeMode: 'light',
    priceSkyCoins: 10,
    previewOrder: 21,
    styleData: JSON.stringify({
      likeColor: '#9D174D',
      commentColor: '#14532D',
      shareColor: '#166534',
      saveColor: '#064E3B',
      giftColor: '#15803D',
    }),
    isActive: true,
  },
  {
    name: 'Garden Icons Dark',
    category: 'icon_color',
    themeMode: 'dark',
    priceSkyCoins: 10,
    previewOrder: 21,
    styleData: JSON.stringify({
      likeColor: '#F9A8D4',
      commentColor: '#86EFAC',
      shareColor: '#BBF7D0',
      saveColor: '#6EE7B7',
      giftColor: '#DCFCE7',
    }),
    isActive: true,
  },

  // ─── Starry Night ─────────────────────────────────────────────────
  {
    name: 'Starry Light',
    category: 'background',
    themeMode: 'light',
    priceSkyCoins: 30,
    previewOrder: 22,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#E0E7FF', '#C7D2FE', '#DDD6FE'],
      locations: [0, 0.5, 1],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#1E1B4B',
      captionColor: '#312E81',
      cornerDecorations: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'star-four-points',
        size: 18,
        color: '#4C1D95',
        opacity: 0.45,
      },
      binderIcon: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'star-four-points',
        color: 'rgba(76,29,149,0.6)',
      },
    }),
    isActive: true,
  },
  {
    name: 'Starry Night',
    category: 'background',
    themeMode: 'dark',
    priceSkyCoins: 30,
    previewOrder: 22,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#0F0A2E', '#312E81', '#1E1B4B'],
      locations: [0, 0.5, 1],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#E0E7FF',
      captionColor: '#C7D2FE',
      cornerDecorations: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'star-four-points',
        size: 18,
        color: '#C4B5FD',
        opacity: 0.45,
      },
      binderIcon: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'star-four-points',
        color: 'rgba(196,181,253,0.6)',
      },
    }),
    isActive: true,
  },
  {
    name: 'Starry Frame',
    category: 'frame',
    themeMode: 'any',
    priceSkyCoins: 20,
    previewOrder: 22,
    styleData: JSON.stringify({
      borderWidth: 2,
      borderColor: '#A78BFA',
      borderRadius: 16,
      shadowColor: '#7C3AED',
      shadowOpacity: 0.35,
      shadowRadius: 12,
      cornerDecorations: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'star-four-points',
        size: 16,
        color: '#A78BFA',
        opacity: 0.8,
      },
    }),
    isActive: true,
  },
  {
    name: 'Starry Icons Light',
    category: 'icon_color',
    themeMode: 'light',
    priceSkyCoins: 12,
    previewOrder: 22,
    styleData: JSON.stringify({
      likeColor: '#5B21B6',
      commentColor: '#4C1D95',
      shareColor: '#6D28D9',
      saveColor: '#3730A3',
      giftColor: '#7C3AED',
    }),
    isActive: true,
  },
  {
    name: 'Starry Icons Dark',
    category: 'icon_color',
    themeMode: 'dark',
    priceSkyCoins: 12,
    previewOrder: 22,
    styleData: JSON.stringify({
      likeColor: '#C4B5FD',
      commentColor: '#DDD6FE',
      shareColor: '#A78BFA',
      saveColor: '#E0E7FF',
      giftColor: '#EDE9FE',
    }),
    isActive: true,
  },

  // ─── Cozy Autumn ──────────────────────────────────────────────────
  {
    name: 'Autumn Light',
    category: 'background',
    themeMode: 'light',
    priceSkyCoins: 25,
    previewOrder: 23,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#FEF3C7', '#FBBF24', '#F59E0B'],
      locations: [0, 0.5, 1],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#451A03',
      captionColor: '#78350F',
      cornerDecorations: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'leaf-maple',
        size: 20,
        color: '#78350F',
        opacity: 0.45,
      },
      binderIcon: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'leaf-maple',
        color: 'rgba(120,53,15,0.6)',
      },
    }),
    isActive: true,
  },
  {
    name: 'Autumn Night',
    category: 'background',
    themeMode: 'dark',
    priceSkyCoins: 25,
    previewOrder: 23,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#1C1207', '#78350F', '#451A03'],
      locations: [0, 0.5, 1],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#FEF3C7',
      captionColor: '#FDE68A',
      cornerDecorations: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'leaf-maple',
        size: 20,
        color: '#FDE68A',
        opacity: 0.4,
      },
      binderIcon: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'leaf-maple',
        color: 'rgba(253,230,138,0.55)',
      },
    }),
    isActive: true,
  },
  {
    name: 'Autumn Frame',
    category: 'frame',
    themeMode: 'any',
    priceSkyCoins: 18,
    previewOrder: 23,
    styleData: JSON.stringify({
      borderWidth: 2,
      borderColor: '#F59E0B',
      borderRadius: 16,
      shadowColor: '#D97706',
      shadowOpacity: 0.3,
      shadowRadius: 10,
      cornerDecorations: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'leaf-maple',
        size: 18,
        color: '#D97706',
        opacity: 0.75,
      },
    }),
    isActive: true,
  },
  {
    name: 'Autumn Icons Light',
    category: 'icon_color',
    themeMode: 'light',
    priceSkyCoins: 10,
    previewOrder: 23,
    styleData: JSON.stringify({
      likeColor: '#991B1B',
      commentColor: '#92400E',
      shareColor: '#78350F',
      saveColor: '#451A03',
      giftColor: '#B45309',
    }),
    isActive: true,
  },
  {
    name: 'Autumn Icons Dark',
    category: 'icon_color',
    themeMode: 'dark',
    priceSkyCoins: 10,
    previewOrder: 23,
    styleData: JSON.stringify({
      likeColor: '#FCA5A5',
      commentColor: '#FDE68A',
      shareColor: '#FCD34D',
      saveColor: '#FEF3C7',
      giftColor: '#FBBF24',
    }),
    isActive: true,
  },

  // ─── Ocean Breeze ─────────────────────────────────────────────────
  {
    name: 'Ocean Light',
    category: 'background',
    themeMode: 'light',
    priceSkyCoins: 25,
    previewOrder: 24,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#CCFBF1', '#99F6E4', '#A5F3FC'],
      locations: [0, 0.5, 1],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#134E4A',
      captionColor: '#115E59',
      cornerDecorations: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'flower-tulip',
        size: 20,
        color: '#115E59',
        opacity: 0.45,
      },
      binderIcon: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'flower-tulip',
        color: 'rgba(17,94,89,0.6)',
      },
    }),
    isActive: true,
  },
  {
    name: 'Ocean Night',
    category: 'background',
    themeMode: 'dark',
    priceSkyCoins: 25,
    previewOrder: 24,
    styleData: JSON.stringify({
      type: 'gradient',
      colors: ['#042F2E', '#134E4A', '#0C4A6E'],
      locations: [0, 0.5, 1],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 1 },
      textColor: '#CCFBF1',
      captionColor: '#99F6E4',
      cornerDecorations: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'flower-tulip',
        size: 20,
        color: '#5EEAD4',
        opacity: 0.4,
      },
      binderIcon: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'flower-tulip',
        color: 'rgba(94,234,212,0.55)',
      },
    }),
    isActive: true,
  },
  {
    name: 'Ocean Frame',
    category: 'frame',
    themeMode: 'any',
    priceSkyCoins: 18,
    previewOrder: 24,
    styleData: JSON.stringify({
      borderWidth: 2,
      borderColor: '#2DD4BF',
      borderRadius: 16,
      shadowColor: '#14B8A6',
      shadowOpacity: 0.3,
      shadowRadius: 10,
      cornerDecorations: {
        iconFamily: 'MaterialCommunityIcons',
        iconName: 'flower-tulip',
        size: 18,
        color: '#14B8A6',
        opacity: 0.75,
      },
    }),
    isActive: true,
  },
  {
    name: 'Ocean Icons Light',
    category: 'icon_color',
    themeMode: 'light',
    priceSkyCoins: 10,
    previewOrder: 24,
    styleData: JSON.stringify({
      likeColor: '#0F766E',
      commentColor: '#115E59',
      shareColor: '#134E4A',
      saveColor: '#042F2E',
      giftColor: '#0D9488',
    }),
    isActive: true,
  },
  {
    name: 'Ocean Icons Dark',
    category: 'icon_color',
    themeMode: 'dark',
    priceSkyCoins: 10,
    previewOrder: 24,
    styleData: JSON.stringify({
      likeColor: '#5EEAD4',
      commentColor: '#99F6E4',
      shareColor: '#A5F3FC',
      saveColor: '#CCFBF1',
      giftColor: '#67E8F9',
    }),
    isActive: true,
  },

  // ─── Light-Theme Icon Colors (dark tones for light backgrounds) ────
  {
    name: 'Deep Earth',
    category: 'icon_color',
    themeMode: 'light',
    priceSkyCoins: 8,
    previewOrder: 10,
    styleData: JSON.stringify({
      likeColor: '#991B1B',
      commentColor: '#1E3A5F',
      shareColor: '#065F46',
      saveColor: '#92400E',
      giftColor: '#7C2D12',
    }),
    isActive: true,
  },
  {
    name: 'Midnight Classic',
    category: 'icon_color',
    themeMode: 'light',
    priceSkyCoins: 6,
    previewOrder: 11,
    styleData: JSON.stringify({
      likeColor: '#BE123C',
      commentColor: '#1E293B',
      shareColor: '#334155',
      saveColor: '#0F172A',
      giftColor: '#78350F',
    }),
    isActive: true,
  },
  {
    name: 'Forest Ink',
    category: 'icon_color',
    themeMode: 'light',
    priceSkyCoins: 8,
    previewOrder: 12,
    styleData: JSON.stringify({
      likeColor: '#9F1239',
      commentColor: '#14532D',
      shareColor: '#1E3A5F',
      saveColor: '#3F3F46',
      giftColor: '#854D0E',
    }),
    isActive: true,
  },

  // ─── Dark-Theme Icon Colors (bright tones for dark backgrounds) ────
  {
    name: 'Starlight',
    category: 'icon_color',
    themeMode: 'dark',
    priceSkyCoins: 8,
    previewOrder: 13,
    styleData: JSON.stringify({
      likeColor: '#FCA5A5',
      commentColor: '#E2E8F0',
      shareColor: '#A5F3FC',
      saveColor: '#FDE68A',
      giftColor: '#FBBF24',
    }),
    isActive: true,
  },
  {
    name: 'Aurora Glow',
    category: 'icon_color',
    themeMode: 'dark',
    priceSkyCoins: 10,
    previewOrder: 14,
    styleData: JSON.stringify({
      likeColor: '#FB7185',
      commentColor: '#67E8F9',
      shareColor: '#A78BFA',
      saveColor: '#34D399',
      giftColor: '#FBBF24',
    }),
    isActive: true,
  },
  {
    name: 'Frosted Neon',
    category: 'icon_color',
    themeMode: 'dark',
    priceSkyCoins: 10,
    previewOrder: 15,
    styleData: JSON.stringify({
      likeColor: '#F472B6',
      commentColor: '#93C5FD',
      shareColor: '#6EE7B7',
      saveColor: '#FCD34D',
      giftColor: '#C084FC',
    }),
    isActive: true,
  },
];

/**
 * Seeds decoration store items on startup.
 * - Fresh install: bulk-creates all items.
 * - Existing data: adds any new items (matched by name + category) without
 *   touching existing rows.
 */
export async function seedDecorations(): Promise<void> {
  try {
    const existingCount = await PostDecoration.count();

    if (existingCount === 0) {
      // Fresh install – seed everything
      const decorations = decorationItems.map(item => ({
        id: uuidv4(),
        ...item,
      }));
      await PostDecoration.bulkCreate(decorations);
      logger.info(`Seeded ${decorations.length} decoration store items`);
      return;
    }

    // Existing data – add any new items that don't exist yet
    let addedCount = 0;
    for (const item of decorationItems) {
      const exists = await PostDecoration.findOne({
        where: { name: item.name, category: item.category },
      });
      if (!exists) {
        await PostDecoration.create({
          id: uuidv4(),
          ...item,
        } as any);
        addedCount++;
      }
    }

    if (addedCount > 0) {
      logger.info(`Added ${addedCount} new decoration store items`);
    } else {
      logger.info(`${existingCount} decorations already exist, no new items to add`);
    }
  } catch (error) {
    logger.error('Failed to seed decorations', { error });
    // Don't throw - this shouldn't crash the server
  }
}

export default seedDecorations;
